---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/Desktop/hosts.yaml"
        group_file: "/Desktop/groups.yaml"
        defaults_file: "/Desktop/defaults.yaml"

